const vetor = [5, 4, 3, 2, 1];
vetor[0] = 1;
vetor[2] = 1;
console.log(vetor);
vetor.push(7);
vetor.push(8);
console.log(vetor);
vetor.pop();
console.log(vetor.pop());
console.log(vetor);
console.log(vetor.length);